// Generated by CoffeeScript 1.3.3
(function() {
  var Appygram, Singleton, request,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Singleton = require('singleton');

  request = require('request');

  Appygram = (function(_super) {

    __extends(Appygram, _super);

    function Appygram() {
      this.setDuplicateLimit = __bind(this.setDuplicateLimit, this);

      this.throttleDuplicate = __bind(this.throttleDuplicate, this);

      this.formatMessage = __bind(this.formatMessage, this);
      this.api_key = void 0;
      this.duplicateLimit = 0;
      this.format = 'json';
      this.endpoint = 'http://api.appygram.com';
      this.version = JSON.parse((require('fs')).readFileSync(__dirname + '/../package.json')).version;
    }

    Appygram.prototype.setApiKey = function(api_key) {
      return this.api_key = api_key;
    };

    Appygram.prototype.errorHandler = function(err, res, req, next) {
      var appy, options, params;
      appy = Appygram.get();
      if (appy.api_key === void 0) {
        return console.error('Please define Appygram\'s API_KEY with appygram.api_key = \'your_api_key\' or appygram.setApiKey(\'your_api_key\')\
        \ If you need an API key please visit http://www.appygram.com/dashboard and request one for your project.');
      } else if (appy.throttleDuplicate(err)) {
        params = {
          api_key: appy.api_key,
          name: "Exception",
          topic: "Exception",
          message: appy.formatMessage(err),
          platform: "appygram-node" + appy.version,
          software: "node application"
        };
        options = {
          uri: appy.endpoint + '/appygrams',
          method: 'POST',
          body: JSON.stringify(params),
          json: true,
          headers: {
            "User-Agent": "appygram-node/" + appy.version,
            "Accept": "application/json",
            "Content-Type": "application/json"
          }
        };
        request(options, function(error, response, body) {
          console.log('Processed appygram');
          if (appy.debug) {
            return next(err);
          }
        });
        if ((next != null) && !appy.debug) {
          return next(err);
        }
      }
    };

    Appygram.prototype.formatMessage = function(error) {
      switch (this.format) {
        case 'json':
          return JSON.stringify(error);
        case 'text':
          return String(error);
      }
    };

    Appygram.prototype.throttleDuplicate = function(error) {
      if (this.duplicateLimit === 0) {
        return true;
      }
    };

    Appygram.prototype.setDuplicateLimit = function(duplicate) {
      return this.duplicateLimit = Number(duplicate);
    };

    return Appygram;

  })(Singleton);

  module.exports = Appygram.get();

}).call(this);
